application: mobicagecloudhr
version: backup-server
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(models|backup)
  script: backup.app
  secure: always

- url: /
  script: config.app
  login: admin
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
